- Gemfile
- Gemfile.lock
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/hosting.rb
- app/models/user.rb
- app/models/visit.rb
- config/routes.rb
- db/migrate/20151223003313_add_user_id_to_visits_and_hostings.rb
- db/schema.rb
- spec/factories/hostings.rb
- spec/factories/visits.rb
Also nested routes accordingly.
> Create associations between user and visits and hostings.

- .gitignore
- Gemfile.lock
* Upgraded gems in Gemfile.
* Added 2 files to .gitignore file
> Upgraded gems in Gemfile and added 2 files to .gitignore file

- README.md
Based on what we did this morning, I added to Contributing section in README file.
Yes, I see an issue with step 4.
> Added to Contributing section in README

- Gemfile.lock
- app/views/home/sign_in.html.erb
> Fixed sign_in spec/test

- app/assets/stylesheets/sign_in.scss
- app/views/users/edit.html.erb
I've gone ahead and styled the users edit page according to the wireframes. glad to work on those emails as soon as I get a chance - hopefully tomorrow or saturday. let me know if you see any changes to be made (i fixed the numbers on the sign in page).
> styled users edit page

- .byebug_history
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/jquery_plugins.js
- app/assets/stylesheets/application.scss
- app/controllers/visits_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- app/views/visits/new.html.erb
From user#show, user can now click a button to go to the form for a new visit and create that visit.
> Add controllers and view for new travel request.

- .byebug_history
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/jquery_plugins.js
- app/assets/stylesheets/application.scss
- app/controllers/hostings_controller.rb
- app/controllers/visits_controller.rb
- app/models/hosting.rb
- app/models/visit.rb
- app/views/hostings/_hosting_form.html.erb
- app/views/hostings/edit.html.erb
- app/views/hostings/new.html.erb
- app/views/layouts/application.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- app/views/visits/_visit_form.html.erb
- app/views/visits/edit.html.erb
- app/views/visits/new.html.erb
- app/views/visits/show.html.erb
- config/routes.rb
- spec/models/hosting_spec.rb
This is a rough version, without the ability to contact hosts and no emails. I will set that up tomorrow. Nearly everything that can be styled on the site is on there now.
> Complete visit and hosting

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
* Upgraded Ruby to 2.3.0.
* Upgrade jbuilder and geocoder gems.
> Upgraded Ruby to 2.3.0 plus 2 gems

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/hostings.scss
- app/assets/stylesheets/sign_in.scss
- app/assets/stylesheets/users.scss
- app/assets/stylesheets/visits.scss
- app/controllers/visits_controller.rb
- app/views/hostings/_hosting_form.html.erb
- app/views/hostings/edit.html.erb
- app/views/hostings/new.html.erb
- app/views/users/show.html.erb
- app/views/visits/_visit_form.html.erb
- app/views/visits/edit.html.erb
- app/views/visits/new.html.erb
- app/views/visits/show.html.erb
i've styled the new and edit hostings/visits pages according to the wireframes - I still need to finish styling the visits show page
> styled hostings/visits pages

- README.md
Add "Used in \<file\> file" to 4 constants in README file.
> Add "Used in ... file" to 4 constants in README file.

- Gemfile
- Gemfile.lock
* Removed comments Gemfile.
* Rearranged groups in Gemfile.
> Removed comments Gemfile; Rearranged groups in Gemfile.

- config/routes.rb
- spec/features/user_signs_up_spec.rb
- spec/spec_helper.rb
- spec/support/features.rb
- spec/support/features/session_helpers.rb
> User signs up specs

- .travis.yml
- config/database.yml.travis
Added .travis.yml + separate config/database.yml.travis file.
Example: https://travis-ci.org/jasnow/BernieBNB/builds/99379077
PS. We can merge the original and new travis database.yml later.
> Added .travis.yml + db config file

- .travis.yml
- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- app/views/layouts/mailer.html.erb
- app/views/layouts/mailer.text.erb
- app/views/user_mailer/contact_host_email.html.erb
- app/views/user_mailer/contact_host_email.text.erb
- app/views/user_mailer/new_host_email.html.erb
- app/views/user_mailer/new_host_email.text.erb
- app/views/user_mailer/welcome_email.html.erb
- app/views/user_mailer/welcome_email.text.erb
- config/environments/development.rb
- config/environments/production.rb
- spec/spec_helper.rb
* Initial work (by me) on Github issue #8: Email Notifications
* Also added 'spec' to rake line in .travis.yml so TravisCI would run the tests too (smile).
* TODOs:
* Get letter_opener to work locally.
* Write specs.
Feedback is welcome.
> [WIP] Github issue #8: Email Notifications

- .byebug_history
- README.md
- app/views/home/sign_in.html.haml
- config/initializers/omniauth.rb
- spec/features/user_signs_up_spec.rb
- spec/spec_helper.rb
Now everyone will need to get keys from google. Added instructions for this to readme
> Adds google auth

- Gemfile
- Gemfile.lock
- app/mailers/application_mailer.rb
- spec/mailers/signup_mailer_spec.rb
- spec/rails_helper.rb
* #8: Emails: Created Signup spec. Needed database_cleaner gem too.
> [WIP] ISS#8: Emails: Created Signup spec

- app/controllers/users_controller.rb
- app/models/user.rb
* Ensures that we have the user's name before sending welcome email.
* Moves the logic for sending welcome email to the controller.
> Move welcome email to UsersContoller#update

- config/environments/production.rb
Links in emails were going to wrong domain, fixed now
> Fix action mailer config for production.

- .gitignore
- .travis.yml
- Gemfile
- Gemfile.lock
- app/views/home/sign_in.html.haml
- spec/spec_helper.rb
Added simplecov gem. Run "COVERAGE='true' rake" to use it.
> Added simplecov gem

- app/controllers/hostings_controller.rb
- app/controllers/users_controller.rb
- app/controllers/visits_controller.rb
- app/models/hosting.rb
Just changed `flash` to `flash.now`. Fixes https://github.com/SandersForPresident/BernieBNB/issues/54
> Clear error messages after successfully creating visit or hosting

- app/controllers/users_controller.rb
- app/views/users/edit.html.haml
- app/views/users/show.html.haml
* Shows a button to delete profile on user's edit page. / Adds associated controller action
* Fixes https://github.com/SandersForPresident/BernieBNB/issues/55
> Add user delete profile

- app/assets/stylesheets/application.scss
- app/views/hostings/edit.html.haml
- app/views/hostings/new.html.haml
- app/views/layouts/application.html.erb
- app/views/users/edit.html.haml
- app/views/users/show.html.haml
- app/views/visits/edit.html.haml
- app/views/visits/new.html.haml
- app/views/visits/show.html.haml
Moved signout button from application layout to line up with the navigation buttons
> Move signout button

- .byebug_history
- app/controllers/hostings_controller.rb
- app/controllers/visits_controller.rb
Resolves https://github.com/SandersForPresident/BernieBNB/issues/60
> current user id matches hosting and visit user ids on controller actions.

- spec/models/hosting_spec.rb
- spec/models/visit_spec.rb
This adds stubs, to mock geocoding in the tests.
Fixes https://github.com/SandersForPresident/BernieBNB/issues/62
> Fix model tests with geocoding

- app/controllers/contacts_controller.rb
- app/decorators/user_decorator.rb
- app/decorators/visit_decorator.rb
- app/mailers/user_mailer.rb
- app/models/hosting.rb
- app/models/visit.rb
- app/views/user_mailer/contact_host_email.html.erb
- app/views/user_mailer/contact_host_email.text.erb
- app/views/visits/_contact_host_instructions.html.haml
- app/views/visits/show.html.haml
- config/routes.rb
The visit show page (host match results) now only allows user to contact a host they have not contacted yet.
Also add methods to user and visit decorators (more to come!)
> Add contact hosts functionality

- app/assets/stylesheets/hostings.scss
- app/assets/stylesheets/visits.scss
- app/views/hostings/_hosting_form.html.haml
- app/views/visits/_visit_form.html.haml
- app/views/visits/edit.html.haml
- app/views/visits/new.html.haml
- app/views/visits/show.html.haml
* Replace nav links on views
* Apply BS button styles
* Add BS form styles to visit form partial
> Refactor visits forms with bootstrap

- app/controllers/users_controller.rb
> Fix email confirmations

- app/assets/stylesheets/users.scss
- app/views/users/edit.html.haml
* Add form classes to form
* Add spacing CSS to users.scss
> Add BS styles to edit profile view

- .gitignore
- app/controllers/feedbacks_controller.rb
- app/mailers/feedback_mailer.rb
- app/models/feedback.rb
- app/views/feedback_mailer/feedback_email.html.erb
- app/views/feedback_mailer/feedback_email.text.erb
- app/views/feedbacks/new.html.erb
- config/routes.rb
'Submit Feedback' feature/initial code
>  [WIP] 'Submit Feedback' feature/initial code 

- app/views/user_mailer/contact_host_email.html.erb
- app/views/user_mailer/contact_host_email.text.erb
> Fix contact host email

- app/assets/stylesheets/visits.scss
- app/views/visits/_empty_visits.html.haml
- app/views/visits/show.html.haml
* Bust empty visits message into partial
* style the header and h1
> Create empty visits partial, style empty visits

- app/models/user.rb
- spec/models/user_spec.rb
Added back non-digit support for phone numbers. Part of #91 .
> Added back non-digit support for phone numbers

- Gemfile.lock
> Upgraded lumberjack gem

- app/views/user_mailer/contact_host_email.html.erb
> Change text in contact email

- app/models/visit.rb
- app/views/visits/show.html.haml
- spec/features/create_visit_spec.rb
* Pass current_user to available_hosts
* Modify query to not include hostings with current_user id
* Modify spec to create second user
> Fix users own hostings showing up with visits

- Gemfile
- Gemfile.lock
- config/locales/en.yml
- spec/models/hosting_spec.rb
- spec/models/visit_spec.rb
* Added more tests for #89 (zipcode validation).
*  Updated validates_timeliness and web-console gems.
> Added more tests for #89 (zipcode validation). Upgraded 2 gems.

- Gemfile
- Gemfile.lock
- app/models/user.rb
- config/puma.rb
- spec/features/create_visit_spec.rb
- spec/models/user_spec.rb
What I have done:
* Wrote more phone number model tests.
* Modified phone number model code using these rules:
* Accept Special chars: blank, ., -, (, )
* Accept Optional leading "1"
* Accept 10-16 digits (shortest: xxxxxxxxxx, longest: 1-(xxx)-xxx-xxxx )
* Need help getting the errors to show up in the flash message in the view.
* Then we can remove the raise exception lines and fix tests.
> [WIP] Fixing phone number model validations

- .travis.yml
- Procfile
- spec/models/user_spec.rb
* Added Procfile for puma webserver setup.
* Uncommented 1 spec in models/user_spec.rb file.
> Added Procfile for puma webserver setup; Uncommented 1 spec

- .travis.yml
Undid auto-deploy work for now.
> Undid auto-deploy work for now

- Gemfile
- app/models/hosting.rb
- app/models/visit.rb
- config/application.rb
- config/database.yml
- config/environments/staging.rb
- config/secrets.yml
- spec/rails_helper.rb
Added 'staging' config environment code.
> Added 'staging' config environment code

- app/assets/stylesheets/users.scss
- app/views/users/show.html.haml
couple tweaks to the /users/show page for the feedback button. can you give me a visual of the page with these changes? sorry, cant get a dev environment working
> Visual tweaks

- Gemfile
Fixed duplicate gem in Gemfile
> Fixed duplicate gem in Gemfile

- Gemfile.lock
- README.md
- app/views/users/edit.html.haml
- spec/features/user_signs_up_spec.rb
- spec/support/feature_test_helper.rb
Added gittip link to README file. Part of #113 .
> Added gittip to README file

- app/assets/javascripts/jquery_plugins.js
- app/views/visits/_hosts.html.haml
- app/views/visits/show.html.haml
Removed part of jQuery method to change button text, moved hosts collection into partial
> Cancel button

- app/views/hostings/edit.html.haml
- app/views/hostings/new.html.haml
- app/views/users/edit.html.haml
- app/views/visits/edit.html.haml
- app/views/visits/new.html.haml
* Cancel button on user#edit links to root is user is not email confirmed, else user's homepage
* Navigation link text changed to "Back" on hosting and visit forms
Fixes #133
> Fix button text/ links

- app/controllers/hostings_controller.rb
- app/views/visits/show.html.haml
- config/initializers/geocoder.rb
* We will use bing geocoding api in production from now on, because it is more generous with free use 
than google
* Submit feedback on visit show page is styled to match user home page.
* Better notifications when a user creates or edits a hosting
> Bing Geocode API in prod/ Style submit feedback/ Hosting notifications

- .travis.yml
- Gemfile
- Gemfile.lock
**TravisCI-to-Heroku changes** based on this blog: http://www.rotati.com/2015/01/basic-automated-deployment-from-travis-ci-to-heroku/
TravisCI Results: https://travis-ci.org/jasnow/BernieBNB/builds/100421388
> TravisCI-to-Heroku changes

- Gemfile.lock
- app/models/hosting.rb
- app/models/visit.rb
- config/initializers/geocoder.rb
- spec/features/user_signs_up_spec_google.rb
- spec/models/hosting_spec.rb
- spec/models/visit_spec.rb
- spec/rails_helper.rb
- spec/support/feature_test_helper.rb
- spec/support/features/session_helpers.rb
* Added Google auth tests.
* Added ":nocov" to exclude code from code analysis for staging/production code.
> Added Google auth tests

- spec/features/create_visit_spec.rb
One more test spec for international phone number support.
> One more test spec for international phone number support

- .travis.yml
- app/models/user.rb
* Added 2 more emails to .travis.yml file.
* Created constants for 2 magic numbers.
> Added 2 more emails to .travis.yml file. Created constants for 2 magic numbers.

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- config/locales/en.yml
- spec/features/create_hosting_spec.rb
- spec/features/user_signs_up_spec.rb
- spec/features/user_signs_up_spec_google.rb
- spec/spec_helper.rb
Set up i18n plus added translations to rspec tests - #153.
> Set up i18n plus added translations to rspec tests #153

- app/models/user.rb
- spec/models/user_spec.rb
Added phone number variable to error messages in model and tests.
> Added phone number var to error messages in model and tests

- app/views/users/edit.html.haml
- spec/features/contact_host_spec.rb
> Match the design on user edit page

- spec/models/user_spec.rb
Added 1 more 'too short' test plus fixed some typos in specs.
> Added 1 more 'too short' test plus fixed some typos in specs

- .travis.yml
Removed berniebnbinfo@gmail.com email from .travis.yml file
> Removed berniebnbinfo@gmail.com email from .travis.yml file

- Gemfile.lock
- config/initializers/faker.rb
- spec/models/user_spec.rb
- spec/models/visit_spec.rb
- spec/rails_helper.rb
Added **Faker::Config.locale = "en-US"** definition to fix Faker issue
References:
* https://github.com/stympy/faker/issues/24
* https://github.com/stympy/faker/issues/10
Also added 3 more tests.
> Added Faker::Config.locale definition to fix Faker issue plus 3 more tests

- spec/models/contact_spec.rb
- spec/rails_helper.rb
* Uncommented js block in rails_helper.rb file.
* Added 1 more test.
> Uncommented js block in rails_helper.rb file; Added 1 more test.

- Gemfile
- Gemfile.lock
- app/models/visit.rb
- config/locales/en.yml
- doc/bbnb.dot
- doc/output_of_bbns_dot.ps
- spec/models/visit_spec.rb
- spec/rails_helper.rb
* Added 1 test and turned off (skip) another test for #182.
* Added zonebie gem to vary time zone for test runs.
* Upgraded rspec_mocks gem.
> Added test and turned off (skip) another test for #182.

- .travis.yml
- Gemfile
- Gemfile.lock
Added 1 gem (quiet_assets); Upgraded 5 gems (travis, sass, orderly, rake, jquery-rails).
> Added 1 gem; Upgraded 5 gems

- Gemfile.lock
- spec/models/visit_spec.rb
* Upgraded email_spec gem.
* Fixed desc line on one test.
> Upgraded email_spec gem; Fixed desc line on one test

- README.md
- spec/models/visit_spec.rb
* Add Facebook/Google set-up info to README for #200 .
* Removed 'skip' for #195 that @jake3030 changed.
> Add info to README for #200; Removed 'skip' for #195

- app/views/hostings/_hosting_form.html.haml
- app/views/visits/_contact_host_instructions.html.haml
Moves host's comments above instructions
> Change hosting comment section to match design.

- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/models/hosting.rb
- app/models/user.rb
- app/models/visit.rb
- app/views/visits/_hosts.html.haml
- db/migrate/20160117222853_change_visit_id_for_contacts.rb
- db/schema.rb
- spec/factories/contacts.rb
- spec/features/contact_host_spec.rb
- spec/features/create_visit_spec.rb
- spec/models/contact_spec.rb
Add tests that hosts can be contacted once per visit, but can be contacted for different visits by the same user.
Update contacts controller to handle new logic and contact.rb
> Change all references to contacts.visitor_id to visit_id

- app/views/pages/stats.html.haml
Removed Travelers and ZipCodes sections from STATS page view. Part of #203 .
> Removed Travelers and ZipCodes sections from STATS page view

- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/views/pages/stats.html.haml
- spec/features/create_visit_spec.rb
Moved incrementing of hostings.contact_counter from model to ContactsController - #190 
See the 3 failed tests that have "skip" in them. Each one has magic numbers [7, 8].
> Partial answer for #190:  Move incrementing of hostings.contact_counter from model to ContactsController

- app/assets/javascripts/policies.coffee
- app/assets/stylesheets/policies.scss
- app/controllers/policies_controller.rb
- app/decorators/policy_decorator.rb
- app/helpers/policies_helper.rb
- config/environments/development.rb
- config/routes.rb
- doc/bernie-bnb-facebook-privacy-statement.txt
- spec/controllers/policies_controller_spec.rb
- spec/decorators/policy_decorator_spec.rb
It is un-styled, but meets minimum FB requirements as a quick fix.
> Add Facebook privacy policy statement

- app/controllers/contacts_controller.rb
- app/mailers/user_mailer.rb
- app/models/hosting.rb
- app/models/visit.rb
- app/views/user_mailer/new_host_email.html.erb
- app/views/user_mailer/new_host_email.text.erb
- config/routes.rb
- spec/mailers/new_host_mailer_spec.rb
Broaden search range to 75 miles to help volunteers in rural areas
Set up route for contacting a host by link in new_host_email
Update email instructions to visitors
> Update for iowa

- app/views/pages/stats.html.haml
Toward #203
Now we show a simple count of number of users, hostings, visits and contacts
> Add basic stats page

- app/views/pages/stats.html.haml
A step toward #225: ugly subsections of 2 of 4 subsections.
> A step toward #225: ugly subsections for 2 of 4 subsections

- app/controllers/contacts_controller.rb
- app/models/hosting.rb
- app/models/visit.rb
Cleaned up the contacts controller a bit
Geocoding now happens before_save so geocoding won't run if other validations fail.
> Refactor contacts controller, move geocoding in lifecycle

- Gemfile.lock
> Upgraded geocoder gem

- app/models/hosting.rb
- app/models/visit.rb
- config/locales/en.yml
- spec/features/create_hosting_spec.rb
This seems to take care of the ugly/ unclear error messages.
> Finish fixing zip code errors

- .rspec
- Gemfile.lock
* Upgraded factory_girl_rails gem.
* Changed comment inside .rspec file.
> Upgraded factory_girl_rails gem

- Gemfile.lock
Upgraded byebug and rspec-rails gems.
> Upgraded byebug and rspec-rails gems

- .gitignore
- Gemfile.lock
* Upgraded simplecov gem.
* Removed 3 files from .gitignore file that are now in my global .gitignore file.
> Upgraded simplecov gem

- Gemfile.lock
Upgrade spring and i18n-tasks gems.
> Upgrade spring and i18n-tasks gems

- Gemfile.lock
Upgraded i18n-tasks and rb-inotify gems.
> Upgraded i18n-tasks and rb-inotify gems

- app/assets/javascripts/application.js
- app/assets/javascripts/facebook.js.erb
- app/assets/javascripts/twitter.js
- app/assets/stylesheets/lib/_share.scss
- app/views/layouts/application.html.erb
- app/views/users/show.html.haml
Share buttons for Facebook and Twitter
> Share buttons

- app/assets/javascripts/facebook.js.erb
Fixes the hardcoded fb app_id from #246
> Changed facebook share link to use ENV variable

- Gemfile
- Gemfile.lock
- app/assets/javascripts/facebook.js.erb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
> Add gon gem to get ENV vars in javascripts

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/routes.rb
- spec/features/contact_host_spec.rb
- spec/features/create_hosting_spec.rb
- spec/features/user_signs_up_spec_facebook.rb
> More error handling specs

- app/assets/stylesheets/users.scss
- app/decorators/hosting_decorator.rb
- app/views/users/show.html.haml
- spec/features/contact_host_spec.rb
- spec/features/create_hosting_spec.rb
- spec/support/feature_test_helper.rb
Changes .date CSS class to .small-details to reuse the style for hosting maximum guests. Update tests to match new text.
> Match hosting buttons to new visit buttons

- Gemfile.lock
Upgraded 4 gems (coderay, geocoder, rspec-core, rubyzip).
> Upgraded 4 gems

- spec/features/user_signs_up_facebook_spec.rb
- spec/features/user_signs_up_google_spec.rb
- spec/support/feature_test_helper.rb
[WIP] A step toward fixing 2 FIXME user_signs_up tests - #271 .
This can be merged safely, but #271 is not done yet.
> [WIP] A step toward fixing 2 FIXME user_signs_up tests

- Gemfile.lock
- app/models/visit.rb
- spec/features/create_visit_spec.rb
* Removed contact_count from visit model. #272 
* Commented out 4 broken asserts associated with #272 .
* Upgraded 3 gems (omniauth-google-oauth2, rake, zonebie).
> [WIP] Started #272 work; Upgraded 3 gems

- Gemfile
- Gemfile.lock
- spec/features/user_signs_up_facebook_spec.rb
- spec/features/user_signs_up_google_spec.rb
- spec/support/feature_test_helper.rb
* Fixed #271 test specs.
* Upgraded parser gem.
> Fixed #271 test specs; Upgraded parser gem

- app/views/user_mailer/contact_host_email.html.erb
- app/views/user_mailer/contact_host_email.text.erb
- app/views/user_mailer/new_host_email.html.erb
- app/views/user_mailer/new_host_email.text.erb
- app/views/visits/_contact_host_instructions.html.haml
> Add instructions to connect over social media

- Gemfile.lock
- spec/support/feature_test_helper.rb
Upgraded 14 gems (geocoder, rake, request_store, timecop, sass, 
websocket, bugsnag, guard-rspec, puma, byebug, capybara, sprockets
factory_girl_rails, factory_girl).
> Upgraded 14 gems

- Gemfile.lock
- spec/features/contact_host_spec.rb
* Fixed #295 bug.
* Upgraded spring gem.
> Fixed #295 bug and upgraded spring gem

- Gemfile.lock
- app/assets/stylesheets/static.scss
- app/controllers/static_controller.rb
- app/decorators/static_decorator.rb
- app/helpers/static_helper.rb
- app/views/pages/faq.html.erb
- config/routes.rb
- spec/controllers/static_controller_spec.rb
- spec/decorators/static_decorator_spec.rb
Merges PR#299 along with my random changes.
> Merges PR#299 along with my random changes

- Gemfile.lock
- app/mailers/feedback_mailer.rb
- app/mailers/user_mailer.rb
- bin/spring
- config/locales/en.yml
- spec/features/contact_host_spec.rb
- spec/mailers/contact_host_mailer_spec.rb
- spec/mailers/new_host_mailer_spec.rb
- spec/mailers/registration_mailer_spec.rb
- spec/mailers/signup_mailer_spec.rb
Started generalizing/i18n (step 1) plus a few more misc changes.
* Added i18n strings to all specs and mailer code. **Not finished but expect safe to merge.**
* Fixed bin/spring script.
* Upgraded [validates_zipcode, geocoder, high_voltage, tins] gems.
Please walk through app on staging before deploying to production.
> Started generalizing/i18n (step 1) plus a few more misc changes

- app/mailers/feedback_mailer.rb
Added missing quote in feedback_mailer.rb
> Added missing quote in feedback_mailer.rb

- Gemfile
- Gemfile.lock
- Rakefile
- spec/features/i18n_spec.rb
Upgraded database_cleaner, i18n_spec gems.
> Upgraded database_cleaner, i18n_spec gems

- config/routes.rb
- spec/features/contact_host_spec.rb
> Remove depracted route and fix related spec

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
I started on issue #267 and was wondering what we wanted to do about the contact page?  Should we make one or just send people to github to contact us?
> starting on footer

- Gemfile
- Gemfile.lock
- config/environments/production.rb
Required to use action mailer with mailgun.
> Add mailgun client

- app/views/pages/faq.html.erb
> Update copy in FAQ

- app/views/user_mailer/new_hosts_digest.html.erb
- config/environments/production.rb
* Reformat digest email.
* Fixed production config file.
> Reformat digest email ; Fixed production config file

- Gemfile.lock
- app/views/user_mailer/new_hosts_digest.html.erb
* For new_hosts_digest.html: Removed boldface, added hr tags.
* Upgraded gems: geocoder, jbuilder, bundler.
> More new_hosts_digest.html tweets plus gem upgrades

- app/controllers/contacts_controller.rb
- app/mailers/user_mailer.rb
- spec/mailers/registration_mailer_spec.rb
- spec/mailers/signup_mailer_spec.rb
Fix a small bug in contacts controller and gives better formatting of email 'from' parameter'.
> Clean up contacts controller

- app/mailers/user_mailer.rb
Small change, merging on green
> Fix sender email address

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- spec/features/redirect_after_sign_in_spec.rb
> Improve redirects

- Gemfile.lock
- spec/features/create_visit_spec.rb
Upgraded 5 gems one last time: [selenium-webdriver, web-console, domain_name, sprockets, bugsnag].
> Upgraded 5 gems one last time.

- .travis.yml
- app/mailers/user_mailer.rb
- app/views/home/sign_in.html.haml
- app/views/user_mailer/goodbye_message.html.erb
- spec/views/home/sign_in.html.haml_spec.rb
> Goodbye message

- app/mailers/user_mailer.rb
- app/views/home/sign_in.html.haml
- app/views/hostings/edit.html.haml
- app/views/user_mailer/new_contacts_digest.html.erb
- app/views/user_mailer/staying_on_message.html.erb
- spec/support/feature_test_helper.rb
- spec/views/home/sign_in.html.haml_spec.rb
> Update site for staying on through convention
